/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  knowledgeBase: [
    "entrypoint",
    {
      type: "category",
      label: "Data",
      collapsed: false,
      items: [
        "knowledge-base/data/data-engineering",
        "knowledge-base/data/data-science",
        "knowledge-base/data/machine-learning",
        {
          type: "category",
          label: "Specialization",
          collapsed: true,
          items: [
            "knowledge-base/data/specialization/gis",
            "knowledge-base/data/specialization/nlp",
            "knowledge-base/data/specialization/visualization",
            "knowledge-base/data/specialization/web-scraping",
          ],
        },
        {
          type: "category",
          label: "Tools",
          collapsed: true,
          items: [
            "knowledge-base/data/tools/jupyter",
            "knowledge-base/data/tools/matplotlib-seaborn",
            "knowledge-base/data/tools/numpy",
            "knowledge-base/data/tools/pandas",
            "knowledge-base/data/tools/pyspark",
            "knowledge-base/data/tools/sklearn",
            "knowledge-base/data/tools/sql",
            {
              type: "category",
              label: "GIS",
              collapsed: true,
              items: [
                "knowledge-base/data/tools/gis/folium",
                "knowledge-base/data/tools/gis/gdal",
                "knowledge-base/data/tools/gis/geopandas",
                "knowledge-base/data/tools/gis/postgis",
                "knowledge-base/data/tools/gis/shapely",
              ],
            },
            {
              type: "category",
              label: "Web Scraping",
              collapsed: true,
              items: [
                "knowledge-base/data/tools/web-scraping/requests",
                "knowledge-base/data/tools/web-scraping/selenium",
                "knowledge-base/data/tools/web-scraping/scrapy",
              ],
            },
          ],
        },
        "knowledge-base/data/misc",
      ],
    },
    {
      type: "category",
      label: "Infra",
      collapsed: false,
      items: [
        "knowledge-base/infra/terraform",
        "knowledge-base/infra/packer",
        "knowledge-base/infra/kubernetes",
        "knowledge-base/infra/aws",
        "knowledge-base/infra/gcp",
      ],
    },
    {
      type: "category",
      label: "DevOps",
      collapsed: true,
      items: [
        "knowledge-base/devops/apache2",
        "knowledge-base/devops/caddy",
        "knowledge-base/devops/cookbook",
        "knowledge-base/devops/devops",
        "knowledge-base/devops/docker",
        "knowledge-base/devops/git",
        "knowledge-base/devops/github",
        "knowledge-base/devops/nix",
        "knowledge-base/devops/unix",
      ],
    },

    {
      type: "category",
      label: "MLOps",
      collapsed: true,
      items: ["knowledge-base/mlops/mlops", "knowledge-base/mlops/dvc"],
    },
    {
      type: "category",
      label: "Database",
      collapsed: true,
      items: [
        "knowledge-base/database/database",
        "knowledge-base/database/sql",
        "knowledge-base/database/postgres",
      ],
    },
    {
      type: "category",
      label: "Software Engineering",
      collapsed: true,
      items: ["knowledge-base/software-engineering/software-engineering"],
    },
    {
      type: "category",
      label: "Platform Engineering",
      collapsed: true,
      items: ["knowledge-base/platform-engineering/platform-engineering"],
    },
    {
      type: "category",
      label: "Python",
      items: [
        "knowledge-base/python/python",
        "knowledge-base/python/recipes",
        {
          type: "category",
          label: "Libraries",
          collapsed: false,
          items: [
            "knowledge-base/python/database",
            "knowledge-base/python/pdf",
            "knowledge-base/python/termcolor",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Programming",
      items: ["knowledge-base/programming/golang"],
    },
    {
      type: "category",
      label: "Shell",
      items: ["knowledge-base/shell/fish"],
    },
    {
      type: "category",
      label: "Misc",
      collapsed: true,
      items: [
        "knowledge-base/misc/misc",
        "knowledge-base/misc/useful-links",
        {
          type: "category",
          label: "Desktop Applications",
          items: [
            "knowledge-base/misc/desktop-app/calibre",
            "knowledge-base/misc/desktop-app/foobar",
            "knowledge-base/misc/desktop-app/mp3tag",
          ],
        },
        "knowledge-base/misc/ffmpeg",
        "knowledge-base/misc/android",
        "knowledge-base/misc/neovim",
        "knowledge-base/misc/osx",
        "knowledge-base/misc/pandoc",
        "knowledge-base/misc/windows",
        "knowledge-base/misc/youtube-dl",
      ],
    },
    "knowledge-base/career",
  ],
  life: [
    "life/celiac",
    "life/repair-shops",
    "life/shopping",
    {
      type: "category",
      label: "Gaming",
      items: [
        "life/gaming/skyrim-mod-list",
        "life/gaming/thesims4",
        "life/gaming/witcher3",
      ],
    },
  ],
  food: ["food/food", "food/easy", "food/desserts"],
};

module.exports = sidebars;
