/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  knowledgeBase: [
    "entrypoint",
    {
      type: "category",
      label: "Data",
      collapsed: false,
      items: [
        "knowledge-base/data/data-engineering",
        "knowledge-base/data/data-science",
        "knowledge-base/data/mlops",
        {
          type: "category",
          label: "Specialization",
          collapsed: true,
          items: [
            "knowledge-base/data/specialization/gis",
            "knowledge-base/data/specialization/nlp",
            "knowledge-base/data/specialization/visualization",
            "knowledge-base/data/specialization/web-scraping",
          ],
        },
        {
          type: "category",
          label: "Tools",
          collapsed: true,
          items: [
            "knowledge-base/data/tools/dvc",
            "knowledge-base/data/tools/jupyter",
            "knowledge-base/data/tools/matplotlib-seaborn",
            "knowledge-base/data/tools/psycopg2",
            "knowledge-base/data/tools/sklearn",

            {
              type: "category",
              label: "GIS",
              collapsed: true,
              items: [
                "knowledge-base/data/tools/gis/folium",
                "knowledge-base/data/tools/gis/gdal",
                "knowledge-base/data/tools/gis/geopandas",
                "knowledge-base/data/tools/gis/postgis",
                "knowledge-base/data/tools/gis/qgis",
                "knowledge-base/data/tools/gis/shapely",
              ],
            },
            {
              type: "category",
              label: "Web Scraping",
              collapsed: true,
              items: [
                "knowledge-base/data/tools/web-scraping/requests",
                "knowledge-base/data/tools/web-scraping/selenium",
                "knowledge-base/data/tools/web-scraping/scrapy",
              ],
            },
            {
              type: "category",
              label: "Wrangling",
              collapsed: true,
              items: [
                "knowledge-base/data/tools/wrangling/numpy",
                "knowledge-base/data/tools/wrangling/pandas",
                "knowledge-base/data/tools/wrangling/pyspark",
                "knowledge-base/data/tools/wrangling/sql",
              ],
            },
          ],
        },
        "knowledge-base/data/misc",
      ],
    },
    {
      type: "category",
      label: "Ops",
      collapsed: true,
      items: [
        "knowledge-base/ops/devops",
        "knowledge-base/ops/sre",
        "knowledge-base/ops/platform-engineering",
        "knowledge-base/ops/finops",
        "knowledge-base/ops/secretops",
        {
          type: "category",
          label: "Base",
          collapsed: false,
          items: [
            "knowledge-base/ops/base/documentation",
            "knowledge-base/ops/base/networking",
            "knowledge-base/ops/base/security",
          ],
        },
        {
          type: "category",
          label: "Cloud",
          collapsed: true,
          items: [
            "knowledge-base/ops/cloud/aws",
            "knowledge-base/ops/cloud/gcp",
            "knowledge-base/ops/cloud/vendors",
          ],
        },
        {
          type: "category",
          label: "Infra",
          collapsed: true,
          items: [
            "knowledge-base/ops/infra/kubernetes",
            "knowledge-base/ops/infra/packer",
            "knowledge-base/ops/infra/terraform",
          ],
        },
        {
          type: "category",
          label: "Unix",
          collapsed: true,
          items: [
            "knowledge-base/ops/unix/unix",
            "knowledge-base/ops/unix/compression",
            "knowledge-base/ops/unix/networking",
            "knowledge-base/ops/unix/system",
          ],
        },
        {
          type: "category",
          label: "Tools",
          collapsed: true,
          items: [
            "knowledge-base/ops/tools/apache2",
            "knowledge-base/ops/tools/caddy",
            "knowledge-base/ops/tools/docker",
            "knowledge-base/ops/tools/git",
            "knowledge-base/ops/tools/github",
            "knowledge-base/ops/tools/neovim",
            "knowledge-base/ops/tools/postgres",
            "knowledge-base/ops/tools/sqlserver",
            "knowledge-base/ops/tools/misc",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Software Engineering",
      collapsed: true,
      items: [
        "knowledge-base/software-engineering/software-engineering",
        "knowledge-base/software-engineering/computer-science",
        "knowledge-base/software-engineering/web-development",
        "knowledge-base/software-engineering/ux-ui",
        "knowledge-base/software-engineering/product-development",
        "knowledge-base/software-engineering/management",
      ],
    },
    {
      type: "category",
      label: "Programming",
      collapsed: true,
      items: [
        "knowledge-base/programming/golang",
        {
          type: "category",
          label: "Python",
          collapsed: true,
          items: [
            "knowledge-base/programming/python/python",
            {
              type: "category",
              label: "Cookbook",
              collapsed: true,
              items: [
                "knowledge-base/programming/python/cookbook/cookbook",
                "knowledge-base/programming/python/cookbook/datetime",
                "knowledge-base/programming/python/cookbook/parallel-processing",
                "knowledge-base/programming/python/cookbook/pdf",
                "knowledge-base/programming/python/cookbook/pytest",
                "knowledge-base/programming/python/cookbook/termcolor",
                "knowledge-base/programming/python/cookbook/yaml",
              ],
            },
          ],
        },
      ],
    },
    "knowledge-base/career",
    {
      type: "category",
      label: "Misc",
      collapsed: true,
      items: [
        "knowledge-base/misc/android",
        "knowledge-base/misc/ffmpeg",
        "knowledge-base/misc/linux",
        "knowledge-base/misc/osx",
        "knowledge-base/misc/pandoc",
        "knowledge-base/misc/useful-links",
        "knowledge-base/misc/windows",
        "knowledge-base/misc/youtube-dl",
        "knowledge-base/misc/misc",
        {
          type: "category",
          label: "Desktop apps",
          collapsed: true,
          items: [
            "knowledge-base/misc/desktop-app/calibre",
            "knowledge-base/misc/desktop-app/foobar",
            "knowledge-base/misc/desktop-app/gpodder",
            "knowledge-base/misc/desktop-app/mp3tag",
          ],
        },
      ],
    },
  ],
  life: [
    "life/celiac",
    "life/repair-shops",
    "life/shopping",
    {
      type: "category",
      label: "Gaming",
      items: [
        "life/gaming/skyrim-mod-list",
        "life/gaming/thesims4",
        "life/gaming/witcher3",
      ],
    },
  ],
  food: ["food/food", "food/easy", "food/desserts"],
};

module.exports = sidebars;
